### ISSUE TITLE
执行第一步安装swoole报了错误

### ISSUE THREAD

**Issue by zzbcraft** [swoole/cpp-swoole#3]
cmake .
sudo make install
如下错误，请问怎么弄？
Linking C shared library lib/libswoole.so
/usr/bin/ld: cannot find -lnghttp2
![image](https://user-images.githubusercontent.com/3115222/27213910-29d0308a-529c-11e7-9fae-ee41c94f05a8.png)

**Comment by matyhtf** [comment]
修改 cmake 文件，去掉 `nghttp2`
